name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the version of Python your project uses

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set permissions for .env file
        run: |
          chmod 600 ./one_health/.env
          
      - name: Load .env file
        run: |
          cp ./one_health/.env .env  # Copy .env.example to .env for testing purposes
          source .env

      - name: Run tests
        run: |
          python manage.py test

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SECRETSSHEC2 }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add SSH key to the agent
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      - name: Set up known_hosts
        run: |
          ssh-keyscan -H 16.171.24.21 >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_rsa ec2-user@16.171.24.21 << 'EOF'
            cd /home/ec2-user/project/one_health
            git pull origin main
            docker-compose down -v
            docker-compose up --build -d
          EOF
